src/Telegram.php
The bug prevented the construction of Telegram objects with a custom HTTP handler, as the Interface could not be found.
=> [Fix] Interface TelegramHttpClientInterface not found

src/Telegram.php
The previous merge request #10 did accidentally not include the interface, it was still broken.
=> [Fix] Fix for merge request #10

src/Objects/Contact.php
Fixed namespace to prevent errors like
```
PHP Fatal error:  Class 'Telegram\Objects\BaseObject' not found in /app/vendor/irazasyed/telegram-bot-sdk/src/Objects/Contact.php on line 6
```
=> [Fix] Telegram\Objects\BaseObject not found in Contact Object class

src/Objects/Message.php, src/Objects/Voice.php, src/Telegram.php
As from the latest [Official API changelog](https://core.telegram.org/bots/api-changelog#august-15-2015)
>August 15, 2015
>Added new type Voice and new method sendVoice for sending voice messages.
>Earlier Audio and sendAudio should now be used for sending music files. Telegram clients will show such files in the in-app music player. If you were using sendAudio for your bot to send voice messages, please use sendVoice instead.
>Added optional fields performer, title to the Audio object and sendAudio method.
>Added optional field voice to the Message object.
This PR adds all new features in the above changelog to the the bot sdk.
=> Added new features from August API Changelog

src/Telegram.php
Now file can be load like resource. For example:   `$telegram->sendDocument($chatId, fopen($imageUrl));`
=> Loading file like resource

src/Api.php
=> More message detection

src/Api.php
Whilst a GET request according to the specs may have an unlimited number of characters, in practice it appears that different versions of PHP and even webbrowsers do have a limit.
http://stackoverflow.com/questions/3091485/what-is-the-limit-on-querystring-get-url-parameters
http://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string
http://stackoverflow.com/questions/7724270/max-size-of-url-parameters-in-get
This means that if we have a very long message etc and try to use a GET request, the request will likely be corrupt.
We can bypass this limitation by using a POST request.
Telegram supports four ways of passing parameters, but the most useful are:
`application/x-www-form-urlencoded`
`multipart/form-data` (use to upload files)
This PR, switches the …
=> Use POST requests when contacting the telegram api server.

upgrade/index.html
Old url is broken, that's why I could use new one:
https://github.com/irazasyed/telegram-bot-sdk/blob/master/docs/changelog.md
But I changed it to the current site page.
=> Changelog broken links fixed (2 links)

src/Objects/BaseObject.php
@irazasyed mapRelatives doesn't really supports initializing inner properties
So for example we get webhook update. Message is transformed to object of Message class, but 'from' and 'chat' fields are not.
This code fixes it. I am not sure if you need that continue, but second if does all the job.
=> Improve mapRelatives in BaseObject

composer.json, src/Api.php, src/Commands/CommandBus.php, src/Laravel/TelegramServiceProvider.php
Use Laravel Container Class to resolve commands type hinted dependencies.
=> Dependency Injection in commands constructors

src/Api.php, src/Commands/Command.php, src/Commands/CommandBus.php, src/Objects/File.php
Removes a few CS warnings and made a couple of areas in the code clearer to understand with more spacing.
=> Mostly codesniffer fixes and some formatting

tests/ApiTest.php, tests/TGMocks.php
Looking for feedback on this.
Have never done testing before, so I'm sure there can be many improvements or better ways to do things. Please show me how! :)
=> Added new tests and created a Mocking 'Telegram Response' class

ruleset.xml
Adding this ruleset for [phpcs](http://cs.sensiolabs.org/) (do not confuse with [php-cs-fxer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)) allows us to ignore some rules which don't suit for this project.
Mainly the line length requirement of 80/120 is broken in various places because of our requirement to add the @methods to the top of some classes. If we were to break the lines up it would look terrible.
If you are using phpstorm, it's very easy to have live notification of phpcs errors. 
* Firstly download/install phpcs any way that suits. In my case I just used the `phpcs.phar` file.
* Add the path to the phar file in phpstorm settings
* Enable the phpcs inspections, to make it acknowledge the custom ruleset, just follow the numbers in this picture:
Your done!
=> Add a custom ruleset file for phpcs.

src/Objects/Chat.php, src/Objects/Message.php, tests/ApiTest.php, tests/CommandBusTest.php, tests/Mocks/MockCommand.php, tests/Mocks/Mocker.php
Some new text was added to the official docs. Reflected in the code now.
Also, I'm confused again about these tests.
I wanted to create a new test class to test the public methods on the `CommandBus.php` file. As I started to write the tests I realised that some of them have already been done from the `ApiTests.php` file.
This is because a lot of the tests in the `ApiTests.php` file, accessed the commandbus object before doing some work. ie `$this->api->addCommands()` is really a helper function/alias for `$this->getCommandBus()->addCommands()`
So where should the tests live? In the api test file or the commandbus test file? I have no idea.
So at the moment about 30% of the `commandBusTests` file has duplicate tests from the api tests.
I'm sure someone will be able to enlighten me on what …
=> Updated some new docs. Added tests for CommandBus

src/Api.php
... and following "Warning:  Invalid argument supplied for foreach()"
=> Prevent "Notice:  Undefined index"

src/Api.php
Fatal error: Call to a member function has() on null in .../vendor/irazasyed/telegram-bot-sdk/src/Api.php on line 870
Appears when is no message received. 
To trigger: just open webhook in browser
=> Prevent Fatal error: Call to a member function has() on null

docs/index.md, docs/upgrade.md, docs/usage/async.md, docs/usage/available-methods-examples.md, docs/usage/commands.md, docs/usage/keyboards.md, docs/usage/webhook-updates.md
The beginnings of some document updates for the release of V2.
=> First draft of docs for Version 2.0 Release

src/Laravel/TelegramServiceProvider.php, src/Laravel/config/telegram.php, tests/ApiTest.php, tests/CommandBusTest.php, tests/Mocks/MockCommandWithDependency.php, tests/Mocks/Mocker.php
This PR [https://github.com/irazasyed/telegram-bot-sdk/pull/53] had a number of issues that I only discovered tonight.
1) The laravel service provider was looking for a config value called: `inject_command_dependencies` yet that value/key is not found in the `telegram.php` config file.
2) The name didn't make sense. We aren't asking the user do they want to inject a dependency, we can't inject anything for them....we are asking do they want their dependency automatically RESOLVED...that we CAN do.
Therefore I added the new key and changed the name to `resolve_command_dependencies`.
3) The service provider was originally registering the commands THEN checking to see should it resolve any dependencies for any commands to be added. It was too late at that stage! 
Changed the order around in …
=> Fix Dependency Injection in command's constructors. With tests.

src/Api.php, src/Objects/Message.php, src/Objects/MessageEntity.php, src/Objects/Venue.php
New API updates 9th April
Implements the following features:
New methods kickChatMember and unbanChatMember.
Added fields venue, pinned_message and entities to the Message object.
Added new objects MessageEntity and Venue, new methods sendVenue and sendContact.
Renamed the fields new_chat_participant and left_chat_participant of the Message object to new_chat_member and left_chat_member.
=> Implement some of new Telegram Bot v2 API updates

src/Helpers/Emojify.php
When writing text, the emoji keyword must be **enclosed** with a colon 
eg
`:smile:`
When converting from emoji back to text, the text word returned will also be enclosed by colons
eg
Before:
`That is great news! smile`
After:
`That is great news! :smile:`
=> Fix Emoji parsing.

src/Helpers/Emojify.php
I think my regexp is not working and it is impossible to solve this problem efficiently with php implementation of regexp functions.
Here is what that is wrong:
input:
':foo:one:foo'
expected output:
':foo1foo:'
current output:
'fooonefoo'
=> Revet regexp

src/Api.php, src/BotsManager.php, src/Keyboard/Button.php, src/Keyboard/Keyboard.php, src/Laravel/config/telegram.php, src/Objects/Message.php, tests/ApiTest.php
It is nice to have some Emoji support. But IMHO, it should be there to be used in the presentation layer. The API layer should not get dirty with it at all. For the performance issues, we can still work on it if we want to.
Sorry for the last PR by the way.
=> no emojify in the API

src/Api.php, src/Events/UpdateWasReceived.php
We need this to be able to call api methods inside other packages which listen to `UpdateWasReceived` event.
E.g. https://github.com/irazasyed/telegram-bot-sdk/blob/master/src/Answers/Answerable.php is used by https://github.com/telegram-bot-kit/talk and of course it needs to be able to make API calls.
=> Inject Api object into UpdateWasReceived event

src/Api.php, src/Objects/Message.php, src/Objects/Update.php
In line with our chat discussion:
- Detection of message type should be concern of Message object --> Moved there
- Detection of Update object added
- Made Api methods more robust against error or updates without message
- Deprecated Api methods
Am i doing this right? (first time github)
Questions:
- Why is `$message->isType` not just an alias for `$message->has`. What does the extra `return $this->detectType() === $type;` add?
- `Api->detectMessageType` was (and is) untested. I honestly do not really know how to test, cause in the end you only test if $update->keys() is implemented correctly. Maybe we need some recorded(?) telegram updates to use as test input.
=> Move type detection from Api class to Message and Update.

src/Api.php, src/Objects/ChatMember.php, src/Objects/EditedMessage.php, src/Objects/Message.php, src/Objects/MessageEntity.php, src/Objects/Sticker.php, src/Objects/Update.php
Implemented recent Telegram API updates.
May 22, 2016
Bot API 2.1. Added more tools for group administrator bots. Your bot can now get a list of administrators and members count in a group, check a user's current status (administrator, creator, left the group, kicked from the group), and leave a group.
Added new methods: getChat, leaveChat, getChatAdministrators, getChatMember, getChatMembersCount.
Added support for edited messages and new mentions from Telegram v.3.9. New fields: edited_message in Update, edit_date in Message, user in MessageEntity. New value text_mention for the type field in MessageEntity.
May 6, 2016
Added the field emoji to the Sticker object. Your bot can now know the emoji a sticker corresponds to.
Added the field forward_from_chat to the Message object for …
=> Implemented recent Telegram API updates.

.travis.yml
Hi..
As you can see PHP 5.5 is already outdated and it's time to drop supporting this version.
http://php.net/supported-versions.php
Regards,
=> Drop PHP 5.5 support

src/Api.php, src/Keyboard/Keyboard.php, src/Methods/AnswerCallbackQuery.php, src/Methods/DeleteWebhook.php, src/Methods/GetUpdates.php, src/Methods/SetGameScore.php, src/Methods/SetWebhook.php, src/Objects/Message.php, src/Objects/Update.php
Apply new BOT API 2.3.1 features.
December 4, 2016
Introducing Bot API 2.3.1, a nifty little update that will give you more control over how your bot gets its updates.
Use the new field max_connections in setWebhook to optimize your bot's server load
Use allowed_updates in setWebhook and getUpdates to selectively subscribe to updates of a certain type. Among other things, this allows you to stop getting updates about new posts in channels where your bot is an admin.
deleteWebhook moved out of setWebhook to get a whole separate method for itself.
=> Apply new BOT API 2.3.1 features. December 4, 2016

src/Objects/Update.php
It does make more sense if `Update->getMessage()` returns any contained message.
Alternatively we could refactor it to `getIncludedMessage()`, as now $update->getMessage() and $update->message could return differently.
=> Improve Update->getMessage()

src/Api.php
I'm using `$update = $telegram->commandsHandler();` in production and discovered that it doesn't use long polling. To make it use long polling I had to rewrite `commandsHandler()` with a call to `getUpdates()` with  `timeout` parameter set.
It would be much simpler to passthrough `timeout` from the scope I'm calling `commandsHandler()` in the first place.
I.e.  `$update = $telegram->commandsHandler(false, ['timeout' => 30]);`
=> pass through params from commandsHandler() to getUpdates()

src/Laravel/TelegramServiceProvider.php
With this improvement you can publish this package's laravel configuration file using
php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider" --tag=config
Or when you publish all your application's configuration file using 
php artisan vendor:publish --tag=config
And if you want to publish all of this package's files regardless of the group, you can still use the default
php artisan vendor:publish --provider="Telegram\Bot\Laravel\TelegramServiceProvider"
=> Added laravel config file to 'config' group

src/Api.php, src/BotsManager.php, src/Commands/CommandBus.php, src/Commands/HelpCommand.php, src/Exceptions/TelegramSDKException.php, src/Exceptions/TelegramUndefinedPropertyException.php, src/FileUpload/InputFile.php, src/HttpClients/GuzzleHttpClient.php, src/Keyboard/Keyboard.php, src/Laravel/Artisan/WebhookCommand.php, src/Methods/Chat.php, src/Methods/EditMessage.php, src/Methods/Game.php, src/Methods/Get.php, src/Methods/Location.php, src/Methods/Message.php, src/Methods/Payments.php, src/Methods/Query.php, src/Methods/Stickers.php, src/Methods/Update.php, src/Objects/Chat.php, src/Objects/ChatMember.php, src/Objects/LoginUrl.php, src/Objects/Message.php, src/Objects/Poll.php, src/Objects/PollOption.php, src/Objects/Update.php, src/TelegramClient.php, src/TelegramResponse.php, tests/Unit/Commands/CommandBusTest.php
All the latest BOT API changes.
=> Latest Bot API changes

src/Methods/Chat.php, src/Methods/Stickers.php, src/Objects/Chat.php, src/Objects/ChatMember.php, src/Objects/ChatPermissions.php, src/Objects/ChatPhoto.php, src/Objects/Sticker.php, src/Objects/StickerSet.php
July 29, 2019
Added support for animated stickers. New field is_animated in Sticker and StickerSet objects, animated stickers can now be used in sendSticker and InlineQueryResultCachedSticker.
Added support for default permissions in groups. New object ChatPermissions, containing actions which a member can take in a chat. New field permissions in the Chat object; new method setChatPermissions.
The field all_members_are_administrators has been removed from the documentation for the Chat object. The field is still returned in the object for backward compatibility, but new bots should use the permissions field instead.
Added support for more permissions for group and supergroup members: added the new field can_send_polls to ChatMember object, added can_change_info, can_invite_users, …
=> Bot API 4.4

src/Answers/Answerable.php, src/Api.php, src/BotsManager.php, src/Keyboard/Base.php, src/Objects/BaseObject.php, src/Objects/InlineQuery/InlineBaseObject.php
String/Array Helpers have been removed in Laravel 6.0, (see https://laravel.com/docs/6.0/upgrade#helpers), fixed it to use the FQCN.
=> Fixed removed string/array helpers for laravel 6

src/Methods/Message.php, src/Traits/Http.php, src/Traits/Validator.php
In the "sendMediaGroup" method the "inputFileField" key has been incorrectly set as "video_note" instead of "media". Also, since the "media" field is JSON serialized string and not an input field, as mentioned in the Telegram API Docs, I updated the "validateInputFileField" in "Traits/Http.php" class to support this case.
Thanks.
=> fix issue in sendMediaGroup
