src/Telegram.php

As per https://github.com/irazasyed/telegram-bot-sdk/issues/13.

Add caption option to sendVideo Method

---

src/Commands/Command.php

Add @methods to class doc block to enable IDE autocomplete on magic methods

---

composer.json
phpunit.xml
tests/ApiTest.php
tests/Mocks/MockCommand.php
tests/Mocks/MockCommandTwo.php

This includes PHPUnit setup and some tests that cover basic API features and command parsing.
API calls and Commands are mocked to allow easy testing.

Some PHPUnit tests #5

---

src/TelegramResponse.php

@irazasyed requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/irazasyed/telegram-bot-sdk/

Scrutinizer Auto-Fixes

---

docs/changelog.md
docs/usage/timeouts.md

Code is in this OR: https://github.com/irazasyed/telegram-bot-sdk/pull/81

Docs for timeout changing ability added

---

src/Api.php

There was wrong default value all that time.

Default timeout fix

---

src/Api.php
src/Objects/InlineQuery.php
src/Objects/Update.php

Here is a simple implementation of bot inline mode.
I've tested this on my own bot. It worked.
If everything is Ok, I will implement tests and docs.
Question: what do you think do we need InlineQueryResult base class with children:  InlineQueryResultArticle,     InlineQueryResultPhoto,     InlineQueryResultGif,     InlineQueryResultMpeg4Gif,     InlineQueryResultVideo?
I think it is not very necessary to create them right now.
Ref TODO: https://github.com/irazasyed/telegram-bot-sdk/issues/95

Inline mode implementation

---

src/Objects/ChosenInlineResult.php
src/Objects/InlineQuery.php
src/Objects/Update.php

Due to new API update I've implemented ChosenInlineResult.
https://core.telegram.org/bots/inline#collecting-feedback
https://core.telegram.org/bots/api#recent-changes
And fixed issues in documentation of InlineQuery.

ChosenInlineResult implementation

---

src/Api.php

As per new blog announcement and changes on the bot api page
https://telegram.org/blog/channels-2-0
https://core.telegram.org/bots/api

Documented new "disable_notification" parameter.

---

src/Objects/Message.php

Very small text change was added to official docs on 30th March 2016.

Synced docblock to match change on official bot api.

---

src/Api.php
src/Objects/UnknownObject.php

Try to make post request in method was not found.

The groundwork for the future Telegram Bot API update

---

tests/ApiTest.php
tests/Mocks/Mocker.php

Remove tests that do not apply to the API class

---

src/Keyboard/Keyboard.php

Fix issue with array to string conversion when trying to use

---

src/Helpers/Emojify.php
tests/ApiTest.php
tests/EmojiSupportTest.php

Fix tests after changes to api and emoji.

Fix broken tests

---

src/Helpers/Emojify.php

Remove unneeded sorting of emojis.

Remove unneeded sorting of emojis.

---

src/Laravel/TelegramServiceProvider.php

Fix. Adds services that are provided by the service provider.

Fix. Adds services that are provided by the service provider.

---

src/Api.php

As discussed the in the slack channel. Provides a way to process a command manually, ie using a queue system etc

Allow updates to be processed for commands manually.

---

src/Api.php
src/BotsManager.php
src/Laravel/config/telegram.php
tests/ApiTest.php

Added ability to disable using emojify

---

src/Laravel/TelegramServiceProvider.php

https://github.com/irazasyed/telegram-bot-sdk/commit/ae214d081928afd4dc9916493768158c28075790#commitcomment-17194269

Fix for object being passed instead of array

---

src/Helpers/Emojify.php

Small tweak with wordToEmoji parsing regex.

Small tweak to word to emoji parsing regex.

---

src/Answers/AnswerBus.php
src/Answers/Answerable.php
src/Commands/Command.php
src/Commands/CommandBus.php

In terms of decoupling (https://github.com/irazasyed/telegram-bot-sdk/pull/171)

Add Answer abstraction layer

---

src/Api.php
src/TelegramResponse.php
tests/ApiTest.php

Make all api method return types consistent with the official API docs.

Make all api method return types consistent with the official API docs.

---

src/Api.php

Warn user when using deprecated methods.

Warn user when using deprecated methods.

---

src/Api.php
src/Objects/BaseObject.php

Inspired by Refactoring to Collections & created alias for better readability.

Inspired by Refactoring to Collections & created alias for better readability.

---

src/Api.php
src/TelegramResponse.php

Fixing some issues on the issue tracker

smallFixes

---

src/Objects/Object.php

Fix Travis build issue.

---

src/Api.php

Update method docblocks to show new InputFile method of uploading/sending files/resources to telegram
Extract code into its own method for better readability.

Code review and docblock updates

---

src/Api.php
src/Traits/Http.php

Make tests work again

---

src/Answers/Answerable.php
src/Objects/Update.php

PR for broken replyWith + callback data

---

src/Objects/Message.php

Added $text property to the Message class + fixed $game desc

---

src/Objects/BaseObject.php
src/Objects/TelegramObject.php

Prevent conflict with reserved key word for class

Fix Php7 Invalid Class Name Issue

---

composer.json
src/Answers/Answerable.php
src/Api.php
src/BotsManager.php
src/Commands/CommandBus.php
src/Exceptions/CouldNotUploadInputFile.php
src/FileUpload/InputFile.php
src/Keyboard/Button.php
src/Keyboard/Keyboard.php
src/Laravel/TelegramServiceProvider.php
src/Methods/Chat.php
src/Methods/EditMessage.php
src/Methods/Game.php
src/Methods/Get.php
src/Methods/Message.php
src/Methods/Query.php
src/Methods/Update.php
src/Objects/BaseObject.php
src/TelegramClient.php
src/TelegramRequest.php
src/Traits/CommandsHandler.php
src/Traits/Http.php
src/Traits/Validator.php
tests/ApiTest.php
tests/CommandBusTest.php
tests/EmojiSupportTest.php
tests/InputFileTest.php
tests/Mocks/Mocker.php

Please do not merge, this PR is to discuss my proposed changes/updates.
Many small commits are made to make it easy to revert something.

Proposed updates

---

src/Laravel/config/telegram.php

Update order of text/settings in the telegram.php config.

---

src/Answers/Answerable.php
src/Commands/Command.php
src/Laravel/config/telegram.php
src/Objects/Update.php
tests/Mocks/Mocker.php

Return an empty collection for better chaining and usability.

Remove nulls and replace with empty collection.

---

src/Answers/Answerable.php

No new feature no bug fix.
Small refactor

Flatten the code

---

src/Objects/User.php

https://core.telegram.org/bots/api#august-23-2017
https://core.telegram.org/bots/api#user

Add User::getIsBot()

---

src/Objects/User.php

Similar to https://github.com/irazasyed/telegram-bot-sdk/pull/438

Add User.isBot property

---

src/Commands/Command.php
src/Commands/CommandBus.php
src/Methods/Update.php
tests/Integration/TelegramApiTest.php
tests/Traits/CommandGenerator.php
tests/Unit/Commands/CommandBusTest.php

Make logic of uploading webhook certificate vs normal upload of other files more consistent.
Move argument detection logic out of commandBus and into the command it actually affects.
Fix some tests and add more coverage.

Multiple Updates and fixes

---

src/Commands/Command.php
tests/Integration/TelegramApiTest.php
tests/Traits/CommandGenerator.php
tests/Unit/Commands/CommandTest.php

New command argument parsing strategy. With tests. For review.

First attempt at new command argument parsing strategy.

---

src/Api.php
src/Keyboard/Keyboard.php
src/Methods/Chat.php
src/Methods/EditMessage.php
src/Methods/Location.php
src/Methods/Message.php
src/Methods/Payments.php
src/Methods/Stickers.php
src/Objects/Chat.php
src/Objects/ChatMember.php
src/Objects/ChatPhoto.php
src/Objects/InlineQuery/InlineQueryResultGif.php
src/Objects/InlineQuery/InlineQueryResultMpeg4Gif.php
src/Objects/MaskPosition.php
src/Objects/Message.php
src/Objects/Payments/Invoice.php
src/Objects/Payments/LabeledPrice.php
src/Objects/Payments/OrderInfo.php
src/Objects/Payments/PreCheckoutQuery.php
src/Objects/Payments/ShippingAddress.php
src/Objects/Payments/ShippingOption.php
src/Objects/Payments/ShippingQuery.php
src/Objects/Payments/SuccessfulPayment.php
src/Objects/Sticker.php
src/Objects/StickerSet.php
src/Objects/Update.php
src/Objects/User.php
src/Objects/VideoNote.php

All the following API changes have been implemented.
Not everything could be tested, due to me not having a payment system setup etc. 
Might be better not to squash all these commits this time.

New official features

---

composer.json

Laravel 5.5 package discovery feature.

Laravel 5.5

---

src/Methods/Message.php

Add VideoNote method

---

src/Actions.php
src/Objects/WebhookInfo.php

Add missing Actions & WebhookInfo property

Add missing object propetry

---

.gitignore
src/Commands/Command.php
src/Objects/BaseObject.php
src/TelegramRequest.php
src/Traits/CommandsHandler.php
src/Traits/Http.php

- juggling equation 
- performance is_null -> null check
- logical operations precedence
- execute() method with lost 3 parameter in CommandsHandle::triggerCommand()

Fix juggling equation, performance with null check and logical ops etc

---

src/Objects/CallbackQuery.php
src/Objects/Update.php

Version 2 - Сallback query

---

src/Objects/Message.php
src/Objects/Update.php

object (or message object) contains a command. This is only true if a
bot_command entity is found.

Small helper functions to check if the Update or Message has a command

---

src/Api.php
src/Objects/BaseObject.php

Changed Str/Arr helpers to FQCN - Laravel 6

---

README.md

Just 2 minor grammatical changes in ReadMe.md.

Minor grammatical changes.

---

tests/Unit/FileUpload/InputFileTest.php

For issue #5
>@irazasyed - #674

Added FileInputTest
